---
title: Minelli Fotografia
timezone: America/Sao_Paulo
collections:
  fotos-principais:
    title: Fotos Principais
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: ":categories/:title.html"
description: My preety awesome Github Pages boilerplate ;)
baseurl: ''
url: 
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
